apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-model-telecom-deployment
spec:
  selector:
    matchLabels:
      app: churn-model-telecom
  replicas: 2
  template:
    metadata:
      labels:
        app: churn-model-telecom
    spec:
      containers:
      - name: churn-model-telecom
        image: deadcomedian/churn_model_telecom:202301221405_30f41d4a4984f9f523dfb662027f37a6a3c0e022
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
